# Generated by Django 4.0.5 on 2022-06-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Created_date', models.CharField(max_length=50)),
                ('Published_date', models.CharField(max_length=50)),
            ],
        ),
    ]
